name: gql_websocket_link
version: 0.2.0
description: GQL Websocket Link
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies: 
  gql: ^0.12.4
  gql_exec: ^0.2.5
  gql_link: ^0.3.1
  meta: ^1.1.8
  rxdart: ^0.25.0
  uuid: ^2.2.2
  web_socket_channel: ^1.1.0
dev_dependencies: 
  gql_pedantic: ^1.0.2
  mockito: ^4.1.1
  test: ^1.14.3
